name: EssentialUtils
description: Folia-compatible survival utilities - Tree Feller, Vein Miner, Auto Farm, Chunk Loader
authors: [ "@cryptofyre", "@PPekKunGzDev" ]
website: https://cryptofy.re
main: net.ppekkungz.essentialUtils.EssentialUtils
version: ${version}
api-version: '1.21'
folia-supported: true
load: POSTWORLD

permissions:
  essentialutils.admin:
    description: Allows access to EssentialUtils admin commands
    default: op
  essentialutils.use:
    description: Allows using EssentialUtils features
    default: true
  essentialutils.treefeller:
    description: Allows using Tree Feller
    default: true
  essentialutils.veinminer:
    description: Allows using Vein Miner
    default: true
  essentialutils.autofarm:
    description: Allows using Auto Farm
    default: true
  essentialutils.chunkloader:
    description: Allows using Chunk Loader to claim farm chunks
    default: true
  essentialutils.chunkloader.bypass:
    description: Bypass chunk loader limits
    default: op
